version: '3.8'

services:
  ai-query:
    image: ghcr.io/nervus-tech/nervus-ai-query:v1.0.0
    container_name: ai-query-prod
    ports:
      - "8119:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ai_query_db
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio_access
      - MINIO_SECRET_KEY=minio_secret
    networks:
      - ai-query-network

networks:
  ai-query-network:
    driver: bridge 